<template>
  <div class="profile-page">
    <section class="section-profile-cover section-shaped my-0">
      <div class="shape shape-style-1 shape-primary shape-skew alpha-4">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </section>
    <section class="section section-skew">
      <div class="container">
        <card shadow class="card-profile mt--500" no-body>
          <div class="px-4">
            <base-alert
              type="danger"
              icon="ni ni-support-16"
              dismissible
              v-if="this.message"
              class="mt-2"
            >
              <span slot="text"
                ><strong>{{ this.message }}</strong></span
              >
            </base-alert>
            <div class="mt-3 py-5 text-center">
              <h2 class="display-3">Check messages</h2>
              <p class="lead text-muted">
                Check your messages to see if they are generated by a bot or
                not. The verification is carried out using a specially trained
                AI, which was trained on a special dataset.
              </p>
              <div class="row justify-content-center">
                <form>
                  <div class="form-group">
                    <textarea
                      class="form-control"
                      id="exampleFormControlTextarea1"
                      rows="3"
                      cols="50"
                      placeholder="Write message to check here"
                      v-validate="'required|min:3'"
                      v-model="check_message_data.message"
                      name="message"
                    ></textarea>
                    <small v-if="errors.has('message')" class="text-danger">
                      {{ errors.first("message") }}
                    </small>
                  </div>
                  <div class="form-group">
                    <base-checkbox
                      name="saveToDb"
                      class="mt-3"
                      v-model="check_message_data.save_to_db"
                    >
                      <span> Save to database </span>
                      <i
                        class="fa fa-info-circle"
                        aria-hidden="true"
                        v-b-popover.hover.right="
                          'You can help us be better by simply saving your messages to further improve the AI. Messages are saved with your anonymity. We save only the text of the message, it will be processed by linguists and psychologists for classification.'
                        "
                        title="Help us be better!"
                      ></i>
                    </base-checkbox>
                  </div>
                  <button
                    id="checkIT"
                    type="button"
                    class="btn btn-primary"
                    @click="checkMessage"
                  >
                    Check IT
                  </button>
                </form>
              </div>
              <div
                class="row p-3 mt-4 border-top align-items-center"
                v-if="is_checked"
              >
                <vc-donut
                  background="white"
                  foreground="grey"
                  :size="300"
                  unit="px"
                  :thickness="20"
                  has-legend
                  legend-placement="top"
                  :sections="sections()"
                  :total="100"
                  :start-angle="0"
                  :auto-adjust-text-size="true"
                  section-mouseover="1"
                  >CheckIT</vc-donut
                >
                <div
                  class="col"
                  style="color: #ff0000"
                  v-if="this.check_result.is_generated"
                >
                  <div class="display-3">This message is genrated by bot</div>
                  <span style="font-size: 150px">
                    <i class="fa fa-android" aria-hidden="true"></i>
                  </span>
                </div>
                <div class="col" style="color: #28a745" v-else>
                  <div class="display-3">This message is written by person</div>
                  <span style="font-size: 150px">
                    <i class="fa fa-user" aria-hidden="true"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </card>
      </div>
    </section>
  </div>
</template>
<script>
import { VBPopover } from "bootstrap-vue/esm/directives/popover/popover";
import CheckService from "../services/check-messages";
import handleError from "./common";

export default {
  data() {
    return {
      is_checked: false,
      message: "",
      check_message_data: {
        message: "",
        save_to_db: false,
      },
      check_result: {
        is_generated: false,
        generated_percent: 0,
      },
    };
  },
  watch: {
    user: {
      check_result(newValue) {
        sections();
      },
      deep: true,
    },
  },

  methods: {
    sections() {
      const genPercent = this.check_result.generated_percent;
      return [
        {
          label: `Generated by bot: ${genPercent}%`,
          value: genPercent,
          color: "#8965e0",
        },
        {
          label: `Written by person: ${(100 - genPercent).toFixed(2)}%`,
          value: 100 - genPercent,
          color: "#1da1f2",
        },
      ];
    },
    checkMessage() {
      this.$validator.validateAll().then((isValid) => {
        if (this.check_message_data.message) {
          CheckService.checkMessage(
            this.check_message_data.message,
            this.check_message_data.save_to_db
          ).then(
            (response) => {
              this.check_result = response.data;
              this.is_checked = true;
            },
            (error) => {
              this.errors, (this.message = handleError(error, this.errors));
            }
          );
        }
      });
    },
  },

  directives: {
    BPopover: VBPopover,
  },
};
</script>
<style>
</style>
